services:
  - type: web
    name: blitzapp
    env: go
    plan: free
    buildCommand: yarn --frozen-lockfile --prod=false && blitz build
    startCommand: blitz start -p ${PORT}
    envVars:
      - key: GO_ENV
        value: production
      - key: SESSION_SECRET_KEY
        generateValue: true   